### ISSUE TITLE
[EPIC] Document the process for setting up notebooks and its different way of usage

### ISSUE THREAD

**Issue by harshad16** [opendatahub-io/notebooks#125]
With the workbench images, a lot of features are made available for the users.
Users might not be aware of all the features and understand each feature, to use it.
Let's provide documentation of each workbench's abilities and features.

List of documentation:
- [x] #160
- [x] #161
- [x] #162  
- [ ] Documentation on Running data-science notebook with most of the important pkgs.
- [ ] Documentation on the usage of the git plugin and s3 plugin
- [ ] Documentation on setup and usage of elyra pipelines.
- [x] https://github.com/opendatahub-io/notebooks/issues/295

**Comment by atheo89** [comment]
Here is the document about notebooks architecture: https://docs.google.com/document/d/1ACmqA7Q_zOUtyAQlFV3c2WZk-cIcYptMdjKcWxOGjfE/edit please, feel free to contribute and enhance it! 
Since, the notebooks repository is currently active, the documentation should require continuous improvements.  Github WIKI could be consider a nice option to transfer the documentation there.

**Comment by jiridanek** [comment]
Closure rationale: the Sep 2, 2026 backlog-refinement decision was that upstream ODH is not under a product-user documentation mandate. Documentation should be added only when it benefits maintainers or downstream users; the broad documentation epic is not planned as stated. Closing as Won't Fix.
