### ISSUE TITLE
[EPIC] Prepare 2023b release version

### ISSUE THREAD

**Issue by harshad16** [opendatahub-io/notebooks#163]
The 2023b version requirements to be ready for incubation, this issue would be used for discussion w.r.t 2023b
Tracked by milestone: [2023b](https://github.com/opendatahub-io/notebooks/milestone/1)

Development:
- [x] https://github.com/opendatahub-io/notebooks/issues/191
- [x] https://github.com/opendatahub-io/notebooks/issues/68
- [x] https://github.com/opendatahub-io/notebooks/issues/72
- [x] https://github.com/opendatahub-io/notebooks/issues/219
- [x] https://github.com/opendatahub-io/notebooks/issues/98
- [x] #235
- [x] https://github.com/opendatahub-io/notebooks/issues/135
- [x] https://github.com/opendatahub-io/notebooks/issues/134
- [x] #237
- [x] https://github.com/opendatahub-io/notebooks/issues/251
- [x] #236
- [x] https://github.com/opendatahub-io/notebooks/issues/192
- [x] #234

Pending:
- [x] https://github.com/opendatahub-io/notebooks/issues/154

QA:
- [ ]  https://github.com/opendatahub-io/notebooks/issues/261

Docs:
- Update the documentation here: https://access.redhat.com/documentation/en-us/red_hat_openshift_data_science/1/html-single/getting_started_with_red_hat_openshift_data_science/index#options-for-notebook-server-environments_get-started

**Comment by adrielparedes** [comment]
@harshad16 can you add a section for each role? One for `Development`, `QE`, and `Docs`?

**Comment by adrielparedes** [comment]
@harshad16 also, I think we should move this to "In Progress" since we are working on this, WDYT?

**Comment by harshad16** [comment]
This is completed overall from the Dev side.
Closing this issue as complete.
Please follow the individual issue for the information.
