### ISSUE TITLE
[EPIC] Notebooks Test Framework Implementation

### ISSUE THREAD

**Issue by atheo89** [opendatahub-io/notebooks#178]
The notebooks currently have minimal test coverage. With this implementation, we want to test with a distinct test_notebook.ipynb file for each notebook, reflecting the specific functionality being tested.

Bellow are the subtask for this work. (May be added more during the implementation)

- [x] https://github.com/opendatahub-io/notebooks/issues/180
- [x] https://github.com/opendatahub-io/notebooks/issues/181
- [x] https://github.com/opendatahub-io/notebooks/issues/182
- [x] https://github.com/opendatahub-io/notebooks/issues/176
- [x] #204

**Comment by harshad16** [comment]
All the parts for Test framework setup is complete.
Further Enhancements will be done as separate tasks. 
Thanks everyone who worked on this.
