### ISSUE TITLE
[Epic] Do some static analysis and content validation on this repository

### ISSUE THREAD

**Issue by jstourac** [opendatahub-io/notebooks#248]
We should perform some static analysis and content structure validation in files in this repository. In ideal case this would allow us to prevent issues like this red-hat-data-services/odh-manifests#500 and point out to some other bugs or bad coding style in our codebase.

What we can do:

- [x] #296
   * addressed in #245 in `main` branch :heavy_check_mark: 
   * `2023b` synced with `main`
- [x] Introduce YAML files validation
   * addressed in #245 in `main` branch :heavy_check_mark:
   * `2023b` synced with `main`
- [x] Introduce YAML files best code practices and linter check
   * addressed in #245 in `main` branch :heavy_check_mark:
   * `2023b` synced with `main`
- [ ] Introduce JSON files best code practices and linter check
- [ ] Introduce Dockerfile validation
- [ ] Introduce Dockerfile files best code practices and linter check

Based on the content of this repository, these checks can cover majority of the files here. More ideas are welcome and we can implement.

**Comment by jstourac** [comment]
Let's also look into this https://pre-commit.com/.

**Comment by jiridanek** [comment]
@coderabbitai evaluate implementation progress as of now, based on what's been committed into the repository

**Comment by jiridanek** [comment]
We use Jira to track work, reopen as tasks in Jira if the interest in this resurfaces.
