### ISSUE TITLE
[tracker] VScode and Rstudio images progress to OOTB defualts.

### ISSUE THREAD

**Issue by harshad16** [opendatahub-io/notebooks#283]
VScode and Rstudio images progress to OOTB defaults.
- [ ] Investigate on the downstream requirements.
     - [ ] If the images can be ported to RHEL/UBI base image or if Centos base images are acceptable. 
- [ ] Set up an environment for the Test instance.

**Comment by jstourac** [comment]
Based on the discussions on meetings, I suppose that we want to also migrate both notebooks from C9S to RHEL9. Guess this is also part of this task?

https://github.com/openshift/release/pull/45089#issuecomment-1792981168

**Comment by chtyler** [comment]
The Jira for the user-facing documentation work is: https://issues.redhat.com/browse/RHODS-12565

**Comment by adrielparedes** [comment]
@harshad16 @atheo89 @jstourac should be split this in 2 different trackers?

**Comment by harshad16** [comment]
This issue is marked as EPIC and all the subsequent requirements are marked as separate Task.
Please follow them. Thanks.

**Comment by harshad16** [comment]
All the described issues are completed.
Closing the issue, thanks for all the work.
