### ISSUE TITLE
Incorporate VS-code workbench to RHOAI

### ISSUE THREAD

**Issue by atheo89** [opendatahub-io/notebooks#320]
Incorporate VS-code workbench to RHOAI

Acceptance criteria:
- [x] Rebase VSCode to UBI instead on C9S 
https://github.com/opendatahub-io/notebooks/pull/319
- [x] Configure the ocp-ci on upstream 
https://github.com/openshift/release/pull/45451 
- [x] Configure ocp-ci to build and push the image on downstream 
https://github.com/openshift/release/pull/45493 
https://github.com/openshift/release/pull/46299
- [x] Update the manifests folder to include the correlated image stream
https://github.com/red-hat-data-services/notebooks/pull/104

- [ ] check for the missing content

https://issues.redhat.com/browse/RHOAIENG-225

**Comment by atheo89** [comment]
In order to facilitate the QE testing on upstream first, we tested if we can rebase the vscode under UBI9. This will help us to have a better stream line between upstream and downstream and keep a better maintenance among both streams.

This PR completes this work on upstream -> https://github.com/opendatahub-io/notebooks/pull/319

The functionality on the VSCode remains the same as in C9S

**Comment by grainnejenningsRH** [comment]
Jira for the user-facing documentation work: https://issues.redhat.com/browse/RHODS-12565

**Comment by harshad16** [comment]
This work is complete now.
Thanks :+1:
