### ISSUE TITLE
Incorporate RStudio workbench to RHOAI

### ISSUE THREAD

**Issue by atheo89** [opendatahub-io/notebooks#321]
Incorporate RStudio workbench to RHOAI

Acceptance criteria:
- [ ] Switch R Studio to be RHEL based  
https://github.com/red-hat-data-services/notebooks/pull/95
- [ ] Configure ocp-ci to build and push the image on downstream
- [ ] Update the manifests folder to include the correlated image stream

JIRA: https://issues.redhat.com/browse/RHOAIENG-314

**Comment by atheo89** [comment]
To install the R language and RStudio IDE on RHEL, it is necessary to enable the `codeready-builder-for-rhel-9-rpms` and `EPEL` repositories. These repositories provide the additional packages required for a successful installation, a way to achieve this is by ensuring entitlements are granted to access the subscription-manager.
Since, we are building our images on OCP-CI it was necessary to  investigate how we can pass the credentials as secrets while the build time. 
After a investigation on if it is feasible to pass credentials as secrets on buildtime, shows that the ocp-ci utilizes the [dockerStrategy](https://docs.ci.openshift.org/docs/architecture/ci-operator/#how-builds-work-in-ci) for image builds. This poses a significant obstacle as it restricts the ability to pass secrets as config maps via build_args. Referencing a pertinent link, it's noted that there are no plans to implement this feature within the specified strategy: https://access.redhat.com/solutions/4501551. In the [documentation](https://docs.ci.openshift.org/docs/how-tos/adding-a-new-secret-to-ci/#use-a-secret-in-a-job-step) for the ocp-ci platform, they outline the utilization of secrets within a job, which, in our case, is not applicable. Our specific requirement involves passing the secret during the buildtime of the image, rather than executing it within the container.

**Comment by grainnejenningsRH** [comment]
Jira for the user-facing documentation work: https://issues.redhat.com/browse/RHODS-12941
